webtalk_init -webtalk_dir /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-05-24 15:25:33" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "og90j7qv5hf3mr8cgod7430c7c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_26" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.099 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.181 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1590310210000" -context "sdk\\\\bsp/1590310210000"
webtalk_add_data -client sdk -key hwid -value "1589638985000" -context "sdk\\\\bsp/1590310210000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1590310210000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1590310210000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1590310210000"
webtalk_add_data -client sdk -key uid -value "1590310211000" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key hwid -value "1589638985000" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key bspid -value "1590310210000" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key projSize -value "4102.37109375" -context "sdk\\\\application/1590310211000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1590326733501"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1590326733501"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1590326733501"
webtalk_add_data -client sdk -key DebugCount -value "46" -context "sdk\\\\bsp/1590326733501"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1590326733501"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1590326733501"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1590326733501"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1590326733501"
webtalk_transmit -clientid 1769577830 -regid "" -xml /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
