webtalk_init -webtalk_dir /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sim/sim_workflow/behav/xsim/xsim.dir/workflow_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 22 09:37:21 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "90a8e36f-d67a-40c3-939c-79975bad9624" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "98229f147b3a49cea9693f6470be4c81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3904.457 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "412 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "121092_KB" -context "xsim\\usage"
webtalk_transmit -clientid 714980490 -regid "" -xml /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sim/sim_workflow/behav/xsim/xsim.dir/workflow_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sim/sim_workflow/behav/xsim/xsim.dir/workflow_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/gennart/Documents/MAI/Thesis/Arithmetic_circuit_Posit_FPGA/Arithmetic_circuit/Arithmetic_circuit.sim/sim_workflow/behav/xsim/xsim.dir/workflow_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
