set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 0.000 [get_ports LD0]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 2.000 [get_ports LD0]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 0.000 [get_ports LD1]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 2.000 [get_ports LD1]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 0.000 [get_ports LD2]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 2.000 [get_ports LD2]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 0.000 [get_ports LD3]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 2.000 [get_ports LD3]
set_output_delay -clock [get_clocks clk_fpga_1] -min -add_delay 0.000 [get_ports LD4]
set_output_delay -clock [get_clocks clk_fpga_1] -max -add_delay 2.000 [get_ports LD4]
set_output_delay -clock [get_clocks clk_fpga_1] -min -add_delay 0.000 [get_ports LD5]
set_output_delay -clock [get_clocks clk_fpga_1] -max -add_delay 2.000 [get_ports LD5]
set_output_delay -clock [get_clocks clk_fpga_1] -min -add_delay 0.000 [get_ports LD6]
set_output_delay -clock [get_clocks clk_fpga_1] -max -add_delay 2.000 [get_ports LD6]
set_output_delay -clock [get_clocks clk_fpga_1] -min -add_delay 0.000 [get_ports LD7]
set_output_delay -clock [get_clocks clk_fpga_1] -max -add_delay 2.000 [get_ports LD7]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]
set_false_path -from [get_pins {BlockDesign/design_1_i/processing_system7_0/inst/PS7_i/FCLKCLK[1]}] -to [get_pins ClkDomSyncer/clk_in_d_reg/D]
set_false_path -from [get_pins workflow_dut/dut_inmod/cdc_dut/i_dst/ack_dst_q_reg/C] -to [get_pins workflow_dut/dut_inmod/cdc_dut/i_src/ack_src_q_reg/D]

set_false_path -from [get_pins {Settings0_reg/r_reg[0]/C}] -to [get_ports LD0]
set_false_path -from [get_pins {Settings0_reg/r_reg[2]/C}] -to [get_ports LD2]
set_false_path -from [get_pins {Settings0_reg/r_reg[3]/C}] -to [get_ports LD3]
set_false_path -from [get_pins {Settings0_reg/r_reg[1]/C}] -to [get_ports LD1]

set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]


